### PR TITLE
Handle columns with reserved names

### LINKED ISSUE #99: MySQL/MariaDB escaped attributes, again
Hi,

first of all. This ticket is about a regression (Issue: #59 fixed in pr #60)  which was introduced with a bugfix (Issues #68 and #62 fixed in pr #85).

So I guess we are victims of dbms incompatibility here. For now I jump back to my workaround mentioned in #59. Can we discuss a way we can handle it properly?

As always, thanks for your hard work with his 👍 

best regards

### PR DESCRIPTION
**Pull request by netpok**
This PR fixes searching columns with reserved names.

The problem was that the column name was not wrapped so it failed when it found a reserved keyword.

I added a new test to prove the fix.

Since the wrapping is handled by the actual grammar it should be correct, it was checked under MySQL and SQLite and it also passed an online Postgres validator.

This PR also makes possible searching in json columns by using `column->jsonProperty` format which worked under MySQL but was broken under MariaDB.

Fixes #99

### CODE REVIEW

**Comment by voydz** [comment]
stellar! thanks for this!

at first glance it seems fine

**Comment by netpok** [comment]
As it turned out this also makes possible searching in json columns by using `column->jsonProperty` format which works under MySQL but breaks under MariaDB.

**Comment by netpok** [comment]
@freekmurze Could you have a look on this? Does this need any more work?

File: src/ModelSearchAspect.php [hunk 1]
```diff
@@ -118,10 +119,18 @@ protected function addSearchConditions(Builder $query, string $term)
         $attributes = $this->attributes;
         $searchTerms = explode(' ', $term);
 
-        $query->where(function (Builder $query) use ($attributes, $term, $searchTerms) {
+        $grammar = $query->getGrammar();
+
+        // Workaround: Laravel 6 incorrectly returns the builder object instead of the grammar
```
Comment (freekmurze) [inline src/ModelSearchAspect.php:124]: Let's just drop support for Laravel 6 in composer.json so we can remove this line.

**Review by freekmurze — CHANGES_REQUESTED** [review]

File: src/ModelSearchAspect.php (hunk 1 above)
Comment (netpok) [reply src/ModelSearchAspect.php:124]: Should I remove it from composer.json or should I just remove the commit and L6 support will be dropped before merging?

Comment (freekmurze) [reply src/ModelSearchAspect.php:124]: Feel free to remove it from composer.json

Comment (netpok) [reply src/ModelSearchAspect.php]: Removed it from composer.json and test runner, also removed the old testbench and phpunit versions too.

Comment (netpok) [reply src/ModelSearchAspect.php]: It looks like It was fixed somewhere in the L7 branch since its broken there on the prefer lowest setting. L7 does not receive security fixes anymore, should I remove that too?

Comment (netpok) [reply src/ModelSearchAspect.php]: I dropped it for now, if it's not needed I will forcepush without the latest commit.

**Comment by freekmurze** [comment]
Thank you very much!
